from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional

Status = Literal["P", "F", "N"]


@dataclass(frozen=True)
class Case:
    case_id: str
    title: str
    steps: str
    expected: str
    test_data: str
    actual: str
    status: Status
    bug_id: Optional[str]
    bug_note: Optional[str]
    severity: Optional[str]


REGISTRATION_CASES = [
    Case(case_id='TC_F01.1', title='Kiểm tra giao diện form đăng ký', steps='Vào /register, quan sát bố cục, tiêu đề, placeholder, nút “Đăng ký”.', expected='Form hiển thị đủ: Họ tên, Email, Mật khẩu, Xác nhận, checkbox điều khoản, nút “Đăng ký”.', test_data='Họ tên: Trần Anh\n Email: anh.tran123@gmail.com\n Mật khẩu: Test@123\n Xác nhận: Test@123', actual='Form hiển thị đủ: Họ tên, Email, Mật khẩu, Xác nhận, checkbox điều khoản, nút “Đăng ký”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.2', title='Kiểm tra label & placeholder', steps='Quan sát các trường.', expected='Có label rõ ràng, placeholder đúng nội dung.', test_data='—', actual='Có label rõ ràng, placeholder đúng nội dung.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.3', title='Kiểm tra nút hành động', steps='Hover nút “Đăng ký”.', expected='Đổi màu đúng style guide, không che chữ.', test_data='—', actual='Đổi màu đúng style guide, không che chữ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.4', title='Kiểm tra responsive', steps='Thu nhỏ độ rộng ~400px.', expected='Form không vỡ; nút xuống dòng đúng vị trí.', test_data='—', actual='Form không vỡ; nút xuống dòng đúng vị trí.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.5', title='Kiểm tra dark mode', steps='Bật dark mode.', expected='Màu chữ/nền tương phản đủ, dễ đọc.', test_data='—', actual='Logo lỗi.', status='F', bug_id='BUG-REG-001', bug_note='Logo bị mờ ở nền tối.', severity='M2'),
    Case(case_id='TC_F01.6', title='Vị trí checkbox điều khoản', steps='Quan sát vị trí.', expected='Checkbox nằm trước dòng “Tôi đồng ý với điều khoản”.', test_data='—', actual='Checkbox nằm trước dòng “Tôi đồng ý với điều khoản”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.7', title='Kiểm tra lỗi chính tả', steps='Đọc nhãn & placeholder.', expected='Không có lỗi chính tả.', test_data='—', actual='Không có lỗi chính tả.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.8', title='Liên kết “Đăng nhập”', steps='Click “Đã có tài khoản?”.', expected='Chuyển hướng tới /login.', test_data='—', actual='Chuyển hướng tới /login.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.9', title='Độ dài form (cuộn ngang)', steps='Cuộn trang.', expected='Không có thanh cuộn ngang.', test_data='—', actual='Không có thanh cuộn ngang.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.10', title='Biểu tượng mắt mật khẩu', steps='Click icon mắt.', expected='Ẩn/hiện ký tự đúng chức năng.', test_data='—', actual='Ẩn/hiện ký tự đúng chức năng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.11', title='Đăng ký hợp lệ', steps='Nhập hợp lệ và submit.', expected='Đăng ký thành công, chuyển về trang chủ, token lưu.', test_data='Họ tên Trần Anh\n Email anh.tran123@gmail.com\n MK Test@123; XN Test@123', actual='Đăng ký thành công, chuyển về trang chủ, token lưu.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.12', title='Email trùng', steps='Dùng email đã tồn tại.', expected='Hiển thị “Email đã được sử dụng. Vui lòng dùng email khác.”', test_data='admin@studio.local', actual='Không chặn email trùng.', status='F', bug_id='BUG-REG-024', bug_note='API chấp nhận email đã tồn tại/ghi đè.', severity='M4'),
    Case(case_id='TC_F01.13', title='Sai định dạng email', steps='Nhập namnam@.', expected='Hiển thị “Email không hợp lệ”.', test_data='namnam@', actual='Không kiểm tra format.', status='F', bug_id='BUG-REG-035', bug_note='Thiếu validate định dạng email.', severity='M4'),
    Case(case_id='TC_F01.14', title='Mật khẩu ngắn', steps='Nhập 123.', expected='Báo “Mật khẩu tối thiểu 6 ký tự và có chữ số.”', test_data='123', actual='Cho submit.', status='F', bug_id='BUG-REG-042', bug_note='Thiếu kiểm tra độ dài MK.', severity='M3'),
    Case(case_id='TC_F01.15', title='MK không có chữ in hoa', steps='Nhập test1234.', expected='Báo yêu cầu đủ điều kiện.', test_data='test1234', actual='Không cảnh báo.', status='F', bug_id='BUG-REG-047', bug_note='Bỏ qua điều kiện chữ hoa.', severity='M3'),
    Case(case_id='TC_F01.16', title='Xác nhận MK khác', steps='Test@123 / Test@124.', expected='Báo “Mật khẩu xác nhận không khớp.”', test_data='MK/XN khác nhau', actual='Gửi request lỗi, không chặn submit.', status='F', bug_id='BUG-REG-055', bug_note='Không khóa submit khi xác nhận sai.', severity='M3'),
    Case(case_id='TC_F01.17', title='Email có khoảng trắng', steps='user demo@gmail.com.', expected='Tự trim, đăng ký bình thường.', test_data='user demo@gmail.com', actual='Lưu kèm khoảng trắng.', status='F', bug_id='BUG-REG-059', bug_note='Không trim email.', severity='M2'),
    Case(case_id='TC_F01.18', title='Email chữ hoa', steps='NamNam@GMAIL.com.', expected='Tự lowercase trước khi lưu.', test_data='Email có chữ HOA', actual='Login phân biệt hoa/thường.', status='F', bug_id='BUG-REG-068', bug_note='Chưa normalize email.', severity='M2'),
    Case(case_id='TC_F01.19', title='Injection ở họ tên', steps='<script>alert(1)</script>.', expected='Hiển thị text thuần, không thực thi.', test_data='Họ tên chứa script', actual='Script thực thi.', status='F', bug_id='BUG-REG-077', bug_note='Lỗi XSS input họ tên.', severity='M4'),
    Case(case_id='TC_F01.20', title='Reset form', steps='Nhấn “Reset”.', expected='Xóa toàn bộ input.', test_data='—', actual='Xóa toàn bộ input.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.21', title='Lỗi server', steps='Giả lập server down.', expected='Hiển thị “Không thể kết nối”.', test_data='—', actual='Hiển thị “Không thể kết nối”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.22', title='Không tick điều khoản', steps='Bỏ chọn checkbox.', expected='Không cho submit.', test_data='—', actual='Không cho submit.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.23', title='Tốc độ phản hồi', steps='Submit hợp lệ.', expected='Thời gian phản hồi < 2s.', test_data='Dữ liệu hợp lệ', actual='Thời gian phản hồi < 2s.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.24', title='Giới hạn email đặc biệt', steps='a@b.c.', expected='Báo lỗi định dạng.', test_data='a@b.c', actual='Báo lỗi định dạng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.25', title='Ký tự đặc biệt trong tên', steps='Nguyễn@Anh.', expected='Báo “Tên không hợp lệ”.', test_data='Họ tên chứa @', actual='Báo “Tên không hợp lệ”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.26', title='MK có ký tự đặc biệt', steps='T@12345.', expected='Cho phép đăng ký.', test_data='T@12345', actual='Cho phép đăng ký.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.27', title='Email hợp lệ chưa verify', steps='Email hợp lệ chưa xác minh.', expected='Cho phép đăng ký, gắn cờ verify=false.', test_data='newuser@demo.com', actual='Cho phép đăng ký, gắn cờ verify=false.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.28', title='Gửi form rỗng', steps='Submit khi trống.', expected='Báo “Vui lòng nhập thông tin”.', test_data='—', actual='Báo “Vui lòng nhập thông tin”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.29', title='Đăng ký → tự đăng nhập', steps='ĐK hợp lệ, quan sát chuyển hướng/token.', expected='Token lưu, header hiển thị tên.', test_data='Trần Anh / anh.tran123@gmail.com / Test@123', actual='Token lưu nhưng header không cập nhật.', status='F', bug_id='BUG-REG-086', bug_note='Lỗi SSR caching.', severity='M4'),
    Case(case_id='TC_F01.30', title='ĐK → logout → login lại', steps='Sau khi ĐK, logout rồi login lại.', expected='Thành công.', test_data='Email anh.tran123@gmail.com / MK Test@123', actual='Thành công.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.31', title='Reload giữa chừng', steps='Nhập dữ liệu rồi F5.', expected='Form rỗng, không gửi request.', test_data='Dữ liệu hợp lệ', actual='Form tự gửi sau reload.', status='F', bug_id='BUG-REG-091', bug_note='Auto-submit.', severity='M3'),
    Case(case_id='TC_F01.32', title='Submit rồi Back', steps='Trong lúc submit nhấn Back.', expected='Cảnh báo “Bạn có muốn rời trang?”.', test_data='Dữ liệu hợp lệ', actual='Cảnh báo hiển thị đúng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.33', title='Submit nhiều lần', steps='Nhấn Submit 3 lần nhanh.', expected='Chỉ gửi 1 request.', test_data='Dữ liệu hợp lệ', actual='Chỉ gửi 1 request.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.34', title='Ghi log hoạt động', steps='Đăng ký thành công.', expected='Log ghi vào DB.', test_data='Dữ liệu hợp lệ', actual='Log ghi vào DB.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.35', title='Trình duyệt khác', steps='Mở Chrome + Edge.', expected='Cả hai đều đăng ký được.', test_data='Email hợp lệ khác nhau', actual='Cả hai đều đăng ký được.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F01.36', title='Lỗi mạng khi submit', steps='Tắt mạng và submit.', expected='Hiển thị “Không thể gửi dữ liệu”.', test_data='Ngắt kết nối trước khi submit', actual='Hiển thị “Không thể gửi dữ liệu”.', status='P', bug_id=None, bug_note=None, severity=None),
]

LOGIN_CASES = [
    Case(case_id='TC_F02.1', title='Giao diện form đăng nhập', steps='Truy cập /login, quan sát bố cục, input, nút “Đăng nhập”.', expected='Hiển thị đúng bố cục, rõ ràng, dễ nhìn.', test_data='/login', actual='Hiển thị đúng bố cục, rõ ràng, dễ nhìn.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.2', title='Placeholder & Label', steps='Quan sát nhãn Email và Mật khẩu.', expected='Có nhãn, placeholder rõ ràng, không lỗi chính tả.', test_data='“Email”, “Mật khẩu”', actual='Có nhãn, placeholder rõ ràng, không lỗi chính tả.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.3', title='Hiển thị lỗi trống', steps='Submit khi chưa nhập.', expected='Hiển thị lỗi “Vui lòng nhập Email / Mật khẩu”.', test_data='(để trống)', actual='Hiển thị lỗi “Vui lòng nhập Email / Mật khẩu”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.4', title='Responsive form', steps='Thu nhỏ trình duyệt 400px.', expected='Form hiển thị gọn, không vỡ layout.', test_data='—', actual='Form hiển thị gọn, không vỡ layout.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.5', title='Nút “Hiện mật khẩu”', steps='Click icon mắt.', expected='Ẩn/hiện ký tự đúng chức năng.', test_data='—', actual='Ẩn/hiện ký tự đúng chức năng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.6', title='Link “Quên mật khẩu?”', steps='Click “Quên mật khẩu?”.', expected='Chuyển hướng /forgot-password.', test_data='—', actual='Chuyển hướng /forgot-password.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.7', title='Link “Đăng ký”', steps='Click “Chưa có tài khoản?”.', expected='Chuyển hướng /register.', test_data='—', actual='Chuyển hướng /register.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.8', title='Dark mode', steps='Bật dark mode.', expected='Nền và chữ tương phản, dễ đọc.', test_data='—', actual='Màu nhạt, khó nhìn.', status='F', bug_id='BUG-LOGIN-001', bug_note='Nút “Đăng nhập” mờ trong dark mode.', severity='M2'),
    Case(case_id='TC_F02.9', title='Đăng nhập hợp lệ', steps='Nhập email hợp lệ và mật khẩu đúng.', expected='Đăng nhập thành công, chuyển đến trang chủ.', test_data='user@gmail.com / Test@123', actual='Đăng nhập thành công, chuyển đến trang chủ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.10', title='Sai mật khẩu', steps='Nhập mật khẩu sai.', expected='Hiển thị thông báo “Sai mật khẩu”.', test_data='user@gmail.com / 123456', actual='Không hiển thị thông báo.', status='F', bug_id='BUG-LOGIN-009', bug_note='Thiếu xử lý lỗi sai mật khẩu.', severity='M3'),
    Case(case_id='TC_F02.11', title='Email không tồn tại', steps='Nhập email chưa đăng ký.', expected='Hiển thị “Tài khoản không tồn tại”.', test_data='abc123@gmail.com / Test@123', actual='Báo lỗi 500.', status='F', bug_id='BUG-LOGIN-011', bug_note='Không xử lý ngoại lệ email không tồn tại.', severity='M4'),
    Case(case_id='TC_F02.12', title='Email sai định dạng', steps='Nhập email sai định dạng.', expected='Báo lỗi “Email không hợp lệ”.', test_data='nam@', actual='Báo lỗi “Email không hợp lệ”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.13', title='Form rỗng', steps='Nhấn submit không nhập dữ liệu.', expected='Báo lỗi “Vui lòng nhập thông tin”.', test_data='(để trống)', actual='Báo lỗi “Vui lòng nhập thông tin”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.14', title='Giới hạn ký tự mật khẩu', steps='Nhập 100 ký tự.', expected='Báo lỗi vượt giới hạn.', test_data='100 ký tự a...a', actual='Báo lỗi vượt giới hạn.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.15', title='Email có khoảng trắng', steps='Nhập “ user@gmail.com ”', expected='Hệ thống tự trim khoảng trắng.', test_data=' user@gmail.com  / Test@123', actual='Vẫn giữ khoảng trắng.', status='F', bug_id='BUG-LOGIN-015', bug_note='Không trim email.', severity='M2'),
    Case(case_id='TC_F02.16', title='Phân biệt hoa thường', steps='Nhập email viết hoa.', expected='Cho phép đăng nhập bình thường.', test_data='User@GMAIL.com / Test@123', actual='Báo sai mật khẩu.', status='F', bug_id='BUG-LOGIN-016', bug_note='So sánh email có phân biệt hoa thường.', severity='M3'),
    Case(case_id='TC_F02.17', title='Tốc độ phản hồi', steps='Đăng nhập hợp lệ.', expected='Phản hồi < 2s.', test_data='user@gmail.com / Test@123', actual='Phản hồi < 2s.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.18', title='Giới hạn retry', steps='Nhập sai 5 lần liên tiếp.', expected='Bị khóa 1 phút.', test_data='user@gmail.com / 123456 (nhập 5 lần)', actual='Bị khóa 1 phút.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.19', title='Thông báo sau đăng nhập', steps='Login thành công.', expected='Hiển thị tên người dùng ở header.', test_data='user@gmail.com / Test@123', actual='Hiển thị tên người dùng ở header.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.20', title='Cookie lưu phiên', steps='Đăng nhập thành công.', expected='Cookie lưu token hợp lệ.', test_data='user@gmail.com / Test@123', actual='Cookie lưu token hợp lệ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.21', title='Tài khoản bị khóa', steps='Dùng user bị khóa.', expected='Báo “Tài khoản bị khóa”.', test_data='lock_user@gmail.com / Test@123', actual='Cho phép đăng nhập.', status='F', bug_id='BUG-LOGIN-021', bug_note='Không kiểm tra trạng thái khóa tài khoản.', severity='M4'),
    Case(case_id='TC_F02.22', title='Tài khoản bị xóa', steps='Nhập user đã xóa.', expected='Báo “Tài khoản không tồn tại”.', test_data='deleted_user@gmail.com / Test@123', actual='Báo “Tài khoản không tồn tại”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.23', title='Remember me', steps='Tick “Ghi nhớ đăng nhập”.', expected='Lưu thông tin user cho lần sau.', test_data='Tick Remember = true', actual='Lưu thông tin user cho lần sau.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.24', title='Bỏ tick remember me', steps='Bỏ tick checkbox.', expected='Không lưu phiên sau khi đóng tab.', test_data='Tick Remember = false', actual='Không lưu phiên sau khi đóng tab.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.25', title='Lỗi mạng', steps='Ngắt mạng khi submit.', expected='Báo lỗi “Không thể kết nối server”.', test_data='Ngắt Wi-Fi trước khi submit', actual='Báo lỗi “Không thể kết nối server”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.26', title='Giới hạn request', steps='Spam 10 lần/s.', expected='Server từ chối (429).', test_data='Gửi 10 request / giây', actual='Server từ chối (429).', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.27', title='Auto focus', steps='Load trang login.', expected='Con trỏ tự focus vào input Email.', test_data='/login', actual='Con trỏ tự focus vào input Email.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.28', title='SQL Injection', steps='Nhập \' OR 1=1 --', expected='Bị chặn, không đăng nhập được.', test_data='\' OR 1=1 --', actual='Cho phép đăng nhập.', status='F', bug_id='BUG-LOGIN-028', bug_note='Không escape input SQL Injection.', severity='M5'),
    Case(case_id='TC_F02.29', title='XSS input', steps='Nhập <script>alert(1)</script>.', expected='Input được sanitize.', test_data='<script>alert(1)</script>', actual='Hiển thị cảnh báo thật.', status='F', bug_id='BUG-LOGIN-029', bug_note='Không chặn XSS.', severity='M4'),
    Case(case_id='TC_F02.30', title='Session timeout', steps='Sau 15 phút không thao tác.', expected='Phiên tự hết hạn.', test_data='Không thao tác 15 phút', actual='Phiên tự hết hạn.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.31', title='Logout', steps='Click “Đăng xuất”.', expected='Quay về trang login, xóa token.', test_data='—', actual='Quay về trang login, xóa token.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.32', title='Đăng nhập → dashboard', steps='Sau khi login, vào /dashboard.', expected='Truy cập thành công.', test_data='user@gmail.com / Test@123', actual='Truy cập thành công.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.33', title='Reload trang', steps='Reload sau khi login.', expected='Giữ trạng thái đăng nhập.', test_data='user@gmail.com / Test@123', actual='Giữ trạng thái đăng nhập.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.34', title='Mở tab mới', steps='Mở tab khác cùng domain.', expected='Giữ phiên login.', test_data='user@gmail.com / Test@123', actual='Giữ phiên login.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.35', title='Đóng trình duyệt', steps='Đóng, mở lại.', expected='Nếu remember me = true → vẫn login.', test_data='Remember = true', actual='Nếu remember me = true → vẫn login.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.36', title='Đăng nhập song song', steps='Login cùng tài khoản ở 2 trình duyệt.', expected='Cho phép 1, đăng xuất phiên cũ.', test_data='Chrome + Edge cùng tài khoản', actual='Cả hai đều hoạt động.', status='F', bug_id='BUG-LOGIN-036', bug_note='Không giới hạn phiên song song.', severity='M3'),
    Case(case_id='TC_F02.37', title='Logout → Back', steps='Sau khi logout, nhấn Back.', expected='Không hiển thị dashboard.', test_data='—', actual='Không hiển thị dashboard.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.38', title='Cập nhật token mới', steps='Token cũ hết hạn.', expected='Hệ thống cấp token mới, không cần login lại.', test_data='Token hết hạn (JWT expired)', actual='Hệ thống cấp token mới, không cần login lại.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.39', title='Tắt mạng khi load dữ liệu', steps='Sau khi login, ngắt mạng.', expected='Hiển thị “Mất kết nối”.', test_data='Ngắt Wi-Fi sau login', actual='Hiển thị “Mất kết nối”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.40', title='Chuyển module khác', steps='Click “Sản phẩm”.', expected='Giữ nguyên phiên.', test_data='Click “/product”', actual='Giữ nguyên phiên.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.41', title='Thiết bị di động', steps='Login trên điện thoại.', expected='Hoạt động bình thường.', test_data='Mobile browser', actual='Hoạt động bình thường.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.42', title='Login Google', steps='Click “Đăng nhập Google”.', expected='Chuyển sang Google Auth, login thành công.', test_data='Tài khoản Google test', actual='Chuyển sang Google Auth, login thành công.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.43', title='Login Facebook', steps='Click “Đăng nhập Facebook”.', expected='Chuyển sang Facebook Auth, login thành công.', test_data='Tài khoản Facebook test', actual='Chuyển sang Facebook Auth, login thành công.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F02.44', title='Lỗi OAuth', steps='Gửi request giả.', expected='Báo “Xác thực thất bại”.', test_data='Request OAuth giả', actual='Báo “Xác thực thất bại”.', status='P', bug_id=None, bug_note=None, severity=None),
]

PRODUCT_LISTING_CASES = [
    Case(case_id='TC_F03.1', title='Giao diện trang sản phẩm', steps='Truy cập /products, quan sát bố cục danh sách, thanh lọc, tiêu đề.', expected='Trang hiển thị đầy đủ danh mục, thanh lọc, danh sách sản phẩm.', test_data='/products', actual='Trang hiển thị đầy đủ danh mục, thanh lọc, danh sách sản phẩm.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.2', title='Hình ảnh sản phẩm', steps='Quan sát ảnh hiển thị.', expected='Ảnh rõ nét, không bị vỡ.', test_data='Hình ảnh “iPhone 14”, “Galaxy S23”', actual='Một số ảnh không tải được.', status='F', bug_id='BUG-PROD-001', bug_note='Hình ảnh lỗi khi file có ký tự đặc biệt.', severity='M3'),
    Case(case_id='TC_F03.3', title='Font chữ và màu sắc', steps='So sánh với mockup.', expected='Font đồng nhất, dễ đọc.', test_data='Giao diện trang sản phẩm', actual='Font đồng nhất, dễ đọc.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.4', title='Nút lọc sản phẩm', steps='Quan sát nút “Lọc”.', expected='Hiển thị rõ, dễ bấm.', test_data='Nút “Lọc”', actual='Hiển thị rõ, dễ bấm.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.5', title='Biểu tượng sắp xếp', steps='Quan sát icon sắp xếp tăng/giảm.', expected='Hiển thị đúng biểu tượng.', test_data='Icon sắp xếp giá', actual='Hiển thị đúng biểu tượng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.6', title='Responsive danh sách', steps='Giảm độ rộng màn hình còn 400px.', expected='Layout tự điều chỉnh, không vỡ.', test_data='Trình duyệt 400px', actual='Layout tự điều chỉnh, không vỡ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.7', title='Hiển thị giá sản phẩm', steps='Quan sát phần giá.', expected='Hiển thị rõ, đơn vị VNĐ.', test_data='Danh sách sản phẩm có giá', actual='Một vài sản phẩm hiển thị “NaN”.', status='F', bug_id='BUG-PROD-007', bug_note='Dữ liệu giá null từ backend.', severity='M4'),
    Case(case_id='TC_F03.8', title='Thanh phân trang', steps='Cuộn xuống cuối trang.', expected='Hiển thị nút “Trang kế tiếp”.', test_data='/products?page=2', actual='Hiển thị nút “Trang kế tiếp”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.9', title='Danh mục bên trái', steps='Quan sát sidebar.', expected='Hiển thị tất cả danh mục.', test_data='Danh mục “Điện thoại”, “Laptop”, “Phụ kiện”', actual='Thiếu danh mục “Phụ kiện”.', status='F', bug_id='BUG-PROD-009', bug_note='API danh mục chưa đồng bộ.', severity='M3'),
    Case(case_id='TC_F03.10', title='Nút “Làm mới”', steps='Quan sát nút reset filter.', expected='Hiển thị rõ, dễ thấy.', test_data='Nút “Làm mới”', actual='Hiển thị rõ, dễ thấy.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.11', title='Màu nền khi hover', steps='Di chuột vào 1 sản phẩm.', expected='Màu nền sáng hơn, border rõ.', test_data='Hover sản phẩm bất kỳ', actual='Màu nền sáng hơn, border rõ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.12', title='Hiển thị số lượng kết quả', steps='Xem phía trên danh sách.', expected='Hiển thị “Tìm thấy X sản phẩm”.', test_data='/products?search=iPhone', actual='Hiển thị “Tìm thấy X sản phẩm”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.13', title='Lọc theo danh mục', steps='Chọn danh mục “Điện thoại”.', expected='Hiển thị sản phẩm “Điện thoại”.', test_data='“Điện thoại”', actual='Hiển thị sản phẩm “Điện thoại”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.14', title='Lọc theo khoảng giá', steps='Nhập giá 1.000.000–5.000.000.', expected='Hiển thị sản phẩm trong khoảng giá.', test_data='1.000.000 – 5.000.000', actual='Hiển thị sản phẩm trong khoảng giá.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.15', title='Lọc theo thương hiệu', steps='Chọn thương hiệu “Samsung”.', expected='Chỉ hiển thị sản phẩm Samsung.', test_data='“Samsung”', actual='Chỉ hiển thị sản phẩm Samsung.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.16', title='Lọc nhiều điều kiện', steps='Chọn danh mục + giá + thương hiệu.', expected='Kết quả đúng với tất cả điều kiện.', test_data='“Điện thoại”, “Samsung”, 1–5 triệu', actual='Kết quả sai.', status='F', bug_id='BUG-PROD-016', bug_note='Kết hợp điều kiện lọc sai logic.', severity='M4'),
    Case(case_id='TC_F03.17', title='Sắp xếp tăng dần theo giá', steps='Chọn “Giá: Thấp → Cao”.', expected='Danh sách sắp đúng.', test_data='Tùy chọn “Giá: Thấp → Cao”', actual='Danh sách sắp đúng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.18', title='Sắp xếp giảm dần theo giá', steps='Chọn “Giá: Cao → Thấp”.', expected='Kết quả đảo chiều đúng.', test_data='“Giá: Cao → Thấp”', actual='Kết quả đảo chiều đúng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.19', title='Lọc theo đánh giá sao', steps='Chọn “Từ 4 sao trở lên”.', expected='Chỉ hiển thị sản phẩm ≥ 4 sao.', test_data='“>=4 sao”', actual='Chỉ hiển thị sản phẩm ≥ 4 sao.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.20', title='Lọc theo tình trạng', steps='Chọn “Còn hàng”.', expected='Ẩn sản phẩm hết hàng.', test_data='“Còn hàng”', actual='Vẫn hiển thị hết hàng.', status='F', bug_id='BUG-PROD-020', bug_note='API không lọc trạng thái tồn kho.', severity='M3'),
    Case(case_id='TC_F03.21', title='Lọc theo khuyến mãi', steps='Chọn “Có khuyến mãi”.', expected='Hiển thị sản phẩm giảm giá.', test_data='“Có khuyến mãi”', actual='Hiển thị sản phẩm giảm giá.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.22', title='Reset bộ lọc', steps='Nhấn “Làm mới”.', expected='Toàn bộ filter trở mặc định.', test_data='Nút “Làm mới”', actual='Toàn bộ filter trở mặc định.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.23', title='Lưu bộ lọc vào URL', steps='Chọn filter, kiểm tra URL.', expected='URL có query tương ứng.', test_data='/products?brand=Samsung', actual='URL có query tương ứng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.24', title='Tải lại trang sau khi lọc', steps='Reload lại trang.', expected='Giữ nguyên kết quả lọc.', test_data='F5 sau lọc', actual='Mất trạng thái lọc.', status='F', bug_id='BUG-PROD-024', bug_note='Không lưu filter trong session.', severity='M3'),
    Case(case_id='TC_F03.25', title='Tìm kiếm sản phẩm theo tên', steps='Nhập “iPhone”.', expected='Hiển thị sản phẩm chứa “iPhone”.', test_data='“iPhone”', actual='Hiển thị sản phẩm chứa “iPhone”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.26', title='Tìm kiếm không kết quả', steps='Nhập “xxxxx”.', expected='Hiển thị “Không tìm thấy sản phẩm”.', test_data='“xxxxx”', actual='Hiển thị “Không tìm thấy sản phẩm”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.27', title='Kiểm tra phân trang', steps='Chuyển sang trang 2.', expected='Hiển thị dữ liệu tiếp theo.', test_data='“Trang 2”', actual='Hiển thị dữ liệu tiếp theo.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.28', title='Tốc độ phản hồi khi lọc', steps='Chọn 1 điều kiện lọc.', expected='Phản hồi < 2 giây.', test_data='“Giá < 5 triệu”', actual='Phản hồi < 2 giây.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.29', title='Lọc với ký tự đặc biệt', steps='Nhập “@#$”.', expected='Báo “Từ khóa không hợp lệ”.', test_data='“@#$”', actual='Cho phép gửi request lỗi.', status='F', bug_id='BUG-PROD-029', bug_note='Không chặn ký tự đặc biệt.', severity='M3'),
    Case(case_id='TC_F03.30', title='Lọc rỗng', steps='Để trống filter.', expected='Hiển thị tất cả sản phẩm.', test_data='(để trống)', actual='Hiển thị tất cả sản phẩm.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.31', title='Lọc nhiều lần liên tục', steps='Click lọc 5 lần nhanh.', expected='Chỉ lấy kết quả cuối.', test_data='5 lần lọc nhanh', actual='Chỉ lấy kết quả cuối.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.32', title='Lọc khi mất mạng', steps='Tắt Wi-Fi khi lọc.', expected='Báo “Không thể kết nối”.', test_data='Ngắt Wi-Fi', actual='Báo “Không thể kết nối”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.33', title='Lọc khi server lỗi 500', steps='Giả lập lỗi 500.', expected='Hiển thị lỗi.', test_data='Lỗi 500 server', actual='Hiển thị lỗi.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.34', title='Lọc bằng phím Enter', steps='Nhập từ khóa rồi Enter.', expected='Hiển thị đúng kết quả.', test_data='“iPhone” + Enter', actual='Hiển thị đúng kết quả.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.35', title='Chuyển đổi sắp xếp', steps='Từ “Giá” sang “Mới nhất”.', expected='Cập nhật lại danh sách.', test_data='“Giá” → “Mới nhất”', actual='Cập nhật lại danh sách.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.36', title='Lọc theo màu sắc', steps='Chọn “Đỏ”.', expected='Hiển thị đúng màu.', test_data='“Đỏ”', actual='Hiển thị đúng màu.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.37', title='Lọc → Xem chi tiết sản phẩm', steps='Lọc danh mục rồi click 1 sản phẩm.', expected='Chuyển sang trang chi tiết đúng.', test_data='“Điện thoại” → click “iPhone”', actual='Chuyển sang trang chi tiết đúng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.38', title='Lọc → Thêm vào giỏ hàng', steps='Lọc rồi thêm vào giỏ.', expected='Thêm đúng sản phẩm đã lọc.', test_data='“Samsung” → Thêm vào giỏ', actual='Thêm đúng sản phẩm đã lọc.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.39', title='Duyệt sản phẩm mới (Admin)', steps='Admin vào mục duyệt.', expected='Hiển thị danh sách chờ duyệt.', test_data='Admin /products/pending', actual='Hiển thị danh sách chờ duyệt.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.40', title='Duyệt sản phẩm hợp lệ', steps='Admin chọn “Duyệt”.', expected='Cập nhật trạng thái “Đã duyệt”.', test_data='Admin → chọn “Duyệt”', actual='Cập nhật trạng thái “Đã duyệt”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.41', title='Duyệt sản phẩm không hợp lệ', steps='Admin chọn “Từ chối”.', expected='Báo “Lý do từ chối”.', test_data='Admin → “Từ chối”', actual='Báo “Lý do từ chối”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.42', title='Tìm kiếm trong trang duyệt', steps='Nhập tên sản phẩm.', expected='Hiển thị sản phẩm khớp tên.', test_data='“iPhone”', actual='Hiển thị sản phẩm khớp tên.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.43', title='Lọc sản phẩm chờ duyệt', steps='Chọn trạng thái “Chờ duyệt”.', expected='Chỉ hiển thị sản phẩm chưa duyệt.', test_data='“Chờ duyệt”', actual='Chỉ hiển thị sản phẩm chưa duyệt.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.44', title='Duyệt hàng loạt', steps='Tick nhiều sản phẩm → Duyệt.', expected='Cập nhật toàn bộ sản phẩm.', test_data='Tick nhiều sản phẩm', actual='Cập nhật toàn bộ sản phẩm.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.45', title='Duyệt → realtime', steps='Một user duyệt, user khác thấy thay đổi.', expected='Giao diện cập nhật ngay.', test_data='2 trình duyệt cùng mở', actual='Không cập nhật realtime.', status='F', bug_id='BUG-PROD-045', bug_note='Socket không đẩy event duyệt.', severity='M4'),
    Case(case_id='TC_F03.46', title='Duyệt → log hệ thống', steps='Sau khi duyệt.', expected='Log ghi vào bảng “approval_logs”.', test_data='Admin duyệt sản phẩm', actual='Log ghi vào bảng “approval_logs”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.47', title='Xuất Excel danh sách', steps='Click “Xuất Excel”.', expected='File tải đầy đủ dữ liệu.', test_data='Nút “Xuất Excel”', actual='File tải đầy đủ dữ liệu.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F03.48', title='Lọc → reload toàn trang', steps='Reload giữa thao tác lọc.', expected='Không mất trạng thái lọc.', test_data='F5 sau thao tác lọc', actual='Mất filter.', status='F', bug_id='BUG-PROD-048', bug_note='Không lưu filter localStorage.', severity='M3'),
]

PRODUCT_DETAIL_CASES = [
    Case(case_id='TC_F04.1', title='Giao diện chi tiết sản phẩm', steps='Truy cập /product/SP001, quan sát bố cục.', expected='Hiển thị đầy đủ ảnh, tên, giá, mô tả, đánh giá.', test_data='/product/SP001', actual='Hiển thị đầy đủ ảnh, tên, giá, mô tả, đánh giá.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.2', title='Ảnh sản phẩm chính', steps='Quan sát ảnh hiển thị chính.', expected='Ảnh rõ nét, đúng tỉ lệ.', test_data='SP001_main.jpg', actual='Ảnh bị méo do CSS không cố định tỷ lệ.', status='F', bug_id='BUG-DETAIL-001', bug_note='CSS không cố định tỷ lệ ảnh.', severity='M3'),
    Case(case_id='TC_F04.3', title='Ảnh phụ', steps='Quan sát danh sách ảnh phụ.', expected='Hiển thị tối đa 5 ảnh phụ.', test_data='SP001 có 4 ảnh phụ', actual='Hiển thị tối đa 5 ảnh phụ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.4', title='Phóng to ảnh', steps='Click vào ảnh chính.', expected='Hiển thị modal phóng to ảnh.', test_data='Ảnh chính SP001', actual='Không phản hồi khi click ảnh.', status='F', bug_id='BUG-DETAIL-002', bug_note='Modal phóng to không hoạt động.', severity='M4'),
    Case(case_id='TC_F04.5', title='Tiêu đề sản phẩm', steps='Quan sát tên sản phẩm.', expected='Hiển thị đúng tên sản phẩm.', test_data='“iPhone 14 Pro”', actual='Hiển thị đúng tên sản phẩm.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.6', title='Giá sản phẩm', steps='Quan sát phần giá.', expected='Hiển thị đúng định dạng VNĐ.', test_data='“25,000,000 VNĐ”', actual='Hiển thị đúng định dạng VNĐ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.7', title='Mô tả chi tiết', steps='Cuộn xuống phần mô tả.', expected='Hiển thị thông tin chi tiết đầy đủ.', test_data='“Màn hình 6.1 inch, chip A16…”', actual='Hiển thị thông tin chi tiết đầy đủ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.8', title='Đánh giá sao', steps='Quan sát khu vực đánh giá.', expected='Hiển thị trung bình sao đúng.', test_data='“4.8/5 (120 đánh giá)”', actual='Sai số trung bình hiển thị.', status='F', bug_id='BUG-DETAIL-003', bug_note='API trả sai giá trị trung bình.', severity='M3'),
    Case(case_id='TC_F04.9', title='Responsive', steps='Thu nhỏ cửa sổ xuống 400px.', expected='Giao diện hiển thị đúng, không vỡ.', test_data='Chrome dev 400px', actual='Giao diện hiển thị đúng, không vỡ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.10', title='Nút hành động', steps='Quan sát “Thêm giỏ”, “Mua ngay”.', expected='Nút hiển thị rõ, dễ thao tác.', test_data='“Thêm vào giỏ”', actual='Nút hiển thị rõ, dễ thao tác.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.11', title='Xem chi tiết sản phẩm hợp lệ', steps='Truy cập /product/SP001.', expected='Hiển thị thông tin đúng.', test_data='SP001', actual='Hiển thị thông tin đúng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.12', title='Xem sản phẩm không tồn tại', steps='Truy cập /product/SP999.', expected='Hiển thị “Không tìm thấy sản phẩm”.', test_data='SP999', actual='Báo lỗi 500 thay vì thông báo “Không tìm thấy sản phẩm”.', status='F', bug_id='BUG-DETAIL-004', bug_note='Backend không xử lý Not Found.', severity='M4'),
    Case(case_id='TC_F04.13', title='Thêm vào giỏ hàng', steps='Click “Thêm vào giỏ”.', expected='Hiển thị “Đã thêm vào giỏ”.', test_data='SP001', actual='Hiển thị “Đã thêm vào giỏ”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.14', title='Mua ngay', steps='Click “Mua ngay”.', expected='Chuyển đến trang thanh toán.', test_data='SP001', actual='Chuyển đến trang thanh toán.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.15', title='Thêm sản phẩm hết hàng', steps='Click “Thêm vào giỏ” khi hết hàng.', expected='Báo “Sản phẩm đã hết hàng”.', test_data='SP010 (hết hàng)', actual='Cho phép thêm vào giỏ.', status='F', bug_id='BUG-DETAIL-005', bug_note='Không kiểm tra tồn kho.', severity='M3'),
    Case(case_id='TC_F04.16', title='Sản phẩm liên quan', steps='Click sản phẩm gợi ý.', expected='Hiển thị chi tiết sản phẩm liên quan.', test_data='SP002', actual='Hiển thị chi tiết sản phẩm liên quan.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.17', title='Đánh giá người dùng', steps='Cuộn xuống phần đánh giá.', expected='Hiển thị danh sách đánh giá.', test_data='user@gmail.com (3 đánh giá)', actual='Hiển thị danh sách đánh giá.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.18', title='Thêm đánh giá mới', steps='Gửi đánh giá 5 sao.', expected='Hiển thị thông báo thành công.', test_data='user@gmail.com / “Sản phẩm rất tốt!”', actual='Hiển thị thông báo thành công.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.19', title='Bình luận trống', steps='Gửi bình luận rỗng.', expected='Báo “Nội dung không được để trống”.', test_data='comment = ', actual='Báo “Nội dung không được để trống”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.20', title='Bình luận có ký tự đặc biệt', steps='Nhập <script>alert(1)</script>.', expected='Hệ thống chặn XSS.', test_data='<script>alert(1)</script>', actual='Hiển thị popup alert(1).', status='F', bug_id='BUG-DETAIL-006', bug_note='Không escape input XSS.', severity='M4'),
    Case(case_id='TC_F04.21', title='Đánh giá đã mua', steps='Người dùng đã mua → đánh giá.', expected='Cho phép đánh giá.', test_data='user@gmail.com (đã mua SP001)', actual='Cho phép đánh giá.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.22', title='Đánh giá chưa mua', steps='Người chưa mua → gửi đánh giá.', expected='Báo “Chỉ người đã mua mới được đánh giá”.', test_data='new_user@gmail.com', actual='Báo “Chỉ người đã mua mới được đánh giá”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.23', title='Tốc độ phản hồi', steps='Mở chi tiết sản phẩm.', expected='<2s.', test_data='SP001', actual='<2s.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.24', title='Mất mạng khi xem chi tiết', steps='Ngắt Wi-Fi.', expected='Hiển thị “Không thể tải dữ liệu”.', test_data='Ngắt Wi-Fi khi mở SP001', actual='Hiển thị “Không thể tải dữ liệu”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.25', title='Breadcrumb', steps='Quan sát điều hướng.', expected='Hiển thị “Trang chủ / Sản phẩm / SP001”.', test_data='SP001', actual='Hiển thị “Trang chủ / Sản phẩm / SP001”.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.26', title='Reload trang chi tiết', steps='Reload /product/SP001.', expected='Giữ nguyên dữ liệu hiển thị.', test_data='F5 tại /product/SP001', actual='Giữ nguyên dữ liệu hiển thị.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.27', title='Thêm giỏ → Mở giỏ hàng', steps='Thêm sản phẩm rồi mở giỏ.', expected='Sản phẩm hiển thị trong giỏ hàng.', test_data='SP001', actual='Sản phẩm hiển thị trong giỏ hàng.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.28', title='Thêm giỏ → Thanh toán', steps='Click “Thanh toán”.', expected='Chuyển đến /checkout.', test_data='SP001', actual='Chuyển đến /checkout.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.29', title='Đánh giá → Reload trang', steps='Reload sau khi gửi đánh giá.', expected='Đánh giá hiển thị lại.', test_data='“5 sao / Rất tốt!”', actual='Đánh giá hiển thị lại.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.30', title='Bình luận → Reload trang', steps='Reload sau khi bình luận.', expected='Bình luận hiển thị lại.', test_data='comment = “Ổn định”', actual='Bình luận hiển thị lại.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.31', title='Thêm giỏ → Duyệt lại', steps='Thêm giỏ, quay lại danh sách, mở lại sản phẩm.', expected='Vẫn lưu trạng thái giỏ.', test_data='SP001', actual='Vẫn lưu trạng thái giỏ.', status='P', bug_id=None, bug_note=None, severity=None),
    Case(case_id='TC_F04.32', title='Đăng xuất → Xem chi tiết', steps='Logout, vào /product/SP001.', expected='Xem được sản phẩm nhưng không thao tác mua.', test_data='user logout', actual='Xem được sản phẩm nhưng không thao tác mua.', status='P', bug_id=None, bug_note=None, severity=None),
]

ALL_CASES = {
    case.case_id: case
    for case in (
        REGISTRATION_CASES
        + LOGIN_CASES
        + PRODUCT_LISTING_CASES
        + PRODUCT_DETAIL_CASES
    )
}
